### ISSUE TITLE
Update docs for V3

### ISSUE THREAD

**Issue by TriPSs** [TriPSs/nestjs-query#130]
## 📚 Documentation

Update the docs with the breaking changes for V3.

**Comment by TriPSs** [comment]
- Updated to latest TypeORM (0.3.15) (If application is not updated some relations will not work / return data)
- Dropped support for NestJS V8

**Comment by hedwiggggg** [comment]
Hello, I have come across a strange behavior in V3 that may be a bug. But possibly it is just a breaking change, so I thought I would ask here. 

So after upgrading from `2.4.0` to `3.0.0-alpha.1` the relational mutations disappear in our project.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/42947316/234516713-3871aac2-c844-425f-8af5-25680cd6cb1b.png">

Is there some kind of configuration that has changed so that by default the relational mutations are no longer generated as well?

**Comment by TriPSs** [comment]
@hedwiggggg this was indeed the breaking change ;) See [here](https://tripss.github.io/nestjs-query/docs/migration-guides/v2.x.x-to-v3.x.x) for more info.
